# Predicting Newsletter Subscription from Player Characteristic 
**Introduction**

    Background

In the gaming world, keeping players engaged and interested is a key focus for game developers. One way companies can do this is through newsletters, which share updates and new events with players. Subscribing to a newsletter often shows that a player is more engaged and invested in the game community. 
By studying which players are likely to subscribe, game developers and marketers can better understand what attracts player interest. This information can help them save resources and time by focusing mainly on the characteristics that sustain player engagement. 

    Question
*Can a player’s experience level and average session time predict whether they subscribe to the game’s newsletter?*

To explore this question, we use two datasets. The players dataset includes each player’s experience level and whether or not they subscribed to the newsletter. The sessions dataset contains information about individual play sessions, including session duration. We calculate each player’s average session time using this data and then merge it with the player information.

In [1]:
#load libraries
library(tidyverse)
library(dplyr)
library(repr)
library(tidymodels)
library(GGally)
library(ISLR)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
── Attaching packages ────────────────────────────────────── tidymodels 1.1.1 ──

✔ broom        1.0.6     ✔ rsample      1.2.1
✔ dials        1.3.0     ✔ tune         1.1.2
✔ infer        1.0.7     ✔ workflows    1.1.4
✔ modeldata    1.4.0     ✔ workflowsets 1.0.1
✔ parsnip      1.2.1     ✔ yardstick    1.3.1
✔ recipes      1.1.0

── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Learn how to get started at https://www.tidymodels.org/start/

Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2

In [2]:
#read in players dataset
url<-"https://raw.githubusercontent.com/garyzhang25/DSI-100-Individual-Project/refs/heads/main/players.csv"
download.file(url, "players.csv")
players_data<-read_csv("players.csv")
head(players_data)

# max, min, mean of hours spent in game and the age
players_max<-players_data |>
select(played_hours, age) |>
map_df(max, na.rm=TRUE)
players_max

players_min<-players_data |>
select(played_hours, age) |>
map_df(min, na.rm=TRUE)
players_min

players_mean<-players_data |>
select(played_hours, age) |>
map_df(mean, na.rm=TRUE)
players_mean

# Each experience level and their count 
players_experience_count<-players_data |>
group_by(experience) |>
summarize(count=n()) |>
arrange(by=desc(count)) 
players_experience_count

# Proportion of subscribers
players_sub_count<- players_data |>
group_by(subscribe) |>
summarize(count=n()) |>
arrange(by=desc(count))
players_sub_count

#genders and count
players_gender_count<- players_data |>
group_by(gender) |>
summarize(count=n()) |>
arrange(by=desc(count))
players_gender_count

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  experience subscribe
1 Pro         TRUE
2 Veteran     TRUE
3 Veteran    FALSE
4 Amateur     TRUE
5 Regular     TRUE
6 Amateur     TRUE
  hashedEmail                                                      played_hours
1 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d 30.3
2 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9  3.8
3 b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28  0.0
4 23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5  0.7
5 7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e  0.1
6 f58aad5996a435f16b0284a3b267f973f9af99e7a89bee0430055a44fa92f977  0.0
  name      gender age
1 Morgan    Male    9
2 Christian Male   17
3 Blake     Male   17
4 Flora     Female 21
5 Kylie     Male   21
6 Adrian    Female 17

  played_hours age
1 223.1        58

  played_hours age
1 0            9

  played_hours age
1 5.845918     21.13918

  experience count
1 Amateur    63
2 Veteran    48
3 Regular    36
4 Beginner   35
5 Pro        14

  subscribe count
1  TRUE     144
2 FALSE      52

  gender            count
1 Male              124
2 Female             37
3 Non-binary         15
4 Prefer not to say  11
5 Two-Spirited        6
6 Agender             2
7 Other               1

In [3]:
url<-"https://raw.githubusercontent.com/garyzhang25/DSI-100-Individual-Project/refs/heads/main/sessions.csv"
download.file(url,"sessions.csv")
sessions_data<-read_csv("sessions.csv")
head(sessions_data)

session_times <- sessions_data |>
  select(start_time, end_time) |>
  separate(start_time,
           into = c("start_date", "start_time"),
           sep = " ",
           convert = TRUE) |>
  separate(end_time, 
           into = c("end_date", "end_time"),
           sep = " ",
           convert = TRUE) |>
  separate(start_time,  
           into = c("start_hour", "start_minute"),
           sep = ":", 
           convert = TRUE) |>
  separate(end_time, 
           into = c("end_hour", "end_minute"),
           sep = ":",
           convert = TRUE) |>
  mutate(start_minute_of_day = start_hour*60 + start_minute) |>
  mutate(end_minute_of_day = end_hour*60 + end_minute) |>
  mutate(session_minutes = end_minute_of_day - start_minute_of_day) |>
  select(session_minutes) |>
  filter(session_minutes >= 0) 
head(session_times)

Rows: 1535 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): hashedEmail, start_time, end_time
dbl (2): original_start_time, original_end_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  hashedEmail
1 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
4 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
5 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
6 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
  start_time       end_time         original_start_time original_end_time
1 30/06/2024 18:12 30/06/2024 18:24 1.71977e+12         1.71977e+12
2 17/06/2024 23:33 17/06/2024 23:46 1.71867e+12         1.71867e+12
3 25/07/2024 17:34 25/07/2024 17:57 1.72193e+12         1.72193e+12
4 25/07/2024 03:22 25/07/2024 03:58 1.72188e+12         1.72188e+12
5 25/05/2024 16:01 25/05/2024 16:12 1.71665e+12         1.71665e+12
6 23/06/2024 15:08 23/06/2024 17:10 1.71916e+12         1.71916e+12

  session_minutes
1  12
2  13
3  23
4  36
5  11
6 122

In [4]:
# max, min, mean of seession time
session_times_max<-session_times |>
map_df(max, na.rm=TRUE)
session_times_max

session_times_min<-session_times |>
map_df(min, na.rm=TRUE)
session_times_min

session_times_average<-session_times |>
map_df(mean, na.rm=TRUE)
session_times_average

  session_minutes
1 256

  session_minutes
1 3

  session_minutes
1 46.85982

In [21]:
#combined data frames and added session time
merged_data <- merge(sessions_data, players_data,by = "hashedEmail")|>
    separate(start_time,
           into = c("start_date", "start_time"),
           sep = " ",
           convert = TRUE) |>
  separate(end_time, 
           into = c("end_date", "end_time"),
           sep = " ",
           convert = TRUE) |>
  separate(start_time,  
           into = c("start_hour", "start_minute"),
           sep = ":", 
           convert = TRUE) |>
  separate(end_time, 
           into = c("end_hour", "end_minute"),
           sep = ":",
           convert = TRUE) |>
  mutate(start_minute_of_day = start_hour*60 + start_minute) |>
  mutate(end_minute_of_day = end_hour*60 + end_minute) |>
  mutate(session_minutes = end_minute_of_day - start_minute_of_day) |>
  filter(session_minutes >= 0) |>
  select(name, session_minutes, experience, subscribe)|>
  group_by(name) |>
  summarize(session_time = mean(session_minutes))

#one name per session_time, select useful columns, and convert subscribe to factor type
clean_data <- merge(players_data, merged_data, by = "name")|>
  select(experience, session_time, subscribe) |>
  mutate(subscribe = as_factor(subscribe))|>
  mutate(subscribe = fct_recode(subscribe, "Yes" = "TRUE", "No" = "FALSE"))
clean_data

    experience session_time subscribe
1   Beginner    18.000000   Yes
2   Amateur     28.000000   Yes
3   Pro         15.000000   Yes
4   Veteran     19.666667   No
5   Regular    150.025641   Yes
6   Amateur     28.357724   Yes
7   Beginner   116.000000   No
8   Beginner    49.000000   Yes
9   Amateur     12.000000   No
10  Regular     25.000000   Yes
11  Beginner    11.021739   No
12  Beginner     5.363636   No
13  Pro         20.500000   Yes
14  Pro        110.000000   No
15  Beginner    66.000000   Yes
16  Beginner    18.000000   No
17  Amateur      8.000000   Yes
18  Regular      5.000000   No
19  Beginner    11.000000   Yes
20  Veteran      8.000000   Yes
21  Veteran      5.000000   No
22  Amateur     11.000000   No
23  Beginner    72.000000   Yes
24  Veteran     10.000000   No
25  Regular     10.000000   Yes
26  Veteran     14.000000   No
27  Amateur     33.000000   Yes
28  Veteran     85.000000   Yes
29  Regular      6.000000   No
30  Veteran    147.000000   Yes
⋮   ⋮          ⋮            ⋮
95  Veteran     11.00000    Yes
96  Amateur     36.00000    No
97  Amateur     64.33333    Yes
98  Veteran     11.00000    No
99  Regular      9.00000    Yes
100 Regular     23.00000    Yes
101 Amateur     24.00000    Yes
102 Pro         80.00000    Yes
103 Regular     10.00000    No
104 Beginner   101.00000    Yes
105 Regular     88.66667    Yes
106 Amateur    136.00000    No
107 Amateur     28.44000    Yes
108 Veteran     61.33333    No
109 Veteran     34.00000    Yes
110 Amateur     12.00000    Yes
111 Veteran     41.00000    Yes
112 Pro         16.00000    Yes
113 Amateur      5.00000    Yes
114 Veteran     10.00000    No
115 Regular     32.15385    Yes
116 Veteran     10.00000    Yes
117 Amateur     75.34375    Yes
118 Beginner     5.00000    Yes
119 Regular     32.00000    Yes
120 Amateur      7.00000    No
121 Veteran     11.00000    Yes
122 Regular     38.00000    Yes
123 Amateur     14.00000    Yes
124 Veteran     16.50000    Yes